[tool.poetry]
name = "lora_sat_decoder"
version = "0.1.0"
description = ""
authors = ["Manuel Rabade <manuel@rabade.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
kaitaistruct = "^0.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
